[project]
name = "kwiddle"
version = "0.1.0"
description = ""
authors = [
    {name = "CloudberryPiTech",email = "bubblesbakale@outlook.com"}
]
readme = "README.md"
requires-python = ">=3.13,<3.16"
dependencies = [
    "pyfiglet (>=1.0.4,<2.0.0)",
    "auto-py-to-exe (>=2.50.1,<3.0.0)",
    "kwbooklib @ git+https://github.com/cloudberrypitech/kwbooklib.git"
]

[tool.poetry]
packages = [{include = "kwiddle", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

